builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - "386"
  main: .
  ldflags: -s -w -X github.com/ahmed-taj/git-todos/cmd.VERSION={{.Version}}
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
  - LICENSE
  - README.md
brew:
  github:
    owner: ahmed-taj
    name: homebrew-git-todos
  folder: Formula
  homepage:  http://git.io/todos
  description: A Git based Todos App for Developers
  commit_author:
    name: Ahmed T. Ali
    email: ah.tajelsir@gmail.com
  dependencies:
    - git
  test: |
    system "#{bin}/git-todos version"
