name: git-todos
version: 0.2.2
summary: A Git based Todos App for Developers
description: >
  Git-todos is Command Line Interface (CLI) that helps to manage local To-Dos
  with ease.

  It aims to help you get things done rather than organizing them. You can use
  Git-todos to add/remove To-Do items locally, import issues from remote
  repositories and to automate the generation of Git commits.

  Git-todos stores To-Dos list locally, and per-repository. For more information
  visit https://git.io/todos.

confinement: strict
grade: stable

parts:
  git:
    plugin: autotools
    build-packages:
      - dh-autoreconf
      - libcurl4-gnutls-dev
      - libexpat1-dev
      - gettext
      - libz-dev
      - libssl-dev
    source: https://github.com/git/git/archive/v2.15.1.tar.gz

  git-todos:
    plugin: dump
    source: https://github.com/ahmed-taj/git-todos/releases/download/v$SNAPCRAFT_PROJECT_VERSION/git-todos_$SNAPCRAFT_PROJECT_VERSION_linux_amd64.tar.gz

apps:
  git-todos:
    command: git-todos
    plugs:
      - home
      - network
